# Generated by Django 4.2.4 on 2023-12-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='gtoken',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
