# Generated by Django 4.2.4 on 2023-12-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_gtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gtoken',
            field=models.CharField(default='0', max_length=225),
        ),
    ]
