# Generated by Django 4.2.4 on 2024-01-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_gtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='gtoken',
        ),
    ]
