# Generated by Django 4.2.4 on 2024-03-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_profile_image_url_profiles_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='image',
            new_name='profile_image_url',
        ),
    ]
